/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_albertsnow_graphicdemo_jni_TestReference */

#ifndef _Included_com_albertsnow_graphicdemo_jni_TestReference
#define _Included_com_albertsnow_graphicdemo_jni_TestReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_albertsnow_graphicdemo_jni_TestReference
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_albertsnow_graphicdemo_jni_TestReference_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
